### ISSUE TITLE
EOSError on Win10

### ISSUE THREAD

**Issue by tueddy** [RRUZ/vcl-styles-utils#167]
We received this bugreport from a customer on Win10:

registered owner   : Windows User
operating system   : Windows 10 x64 build 10240
system language    : German

exception number   : 1
exception class    : EOSError
exception message  : Ein Aufruf einer Betriebssystemfunktion ist fehlgeschlagen.

main thread ($3e64):
00460a59 +81 PdfEditor.exe System.SysUtils                    RaiseLastOSError
004609cf +07 PdfEditor.exe System.SysUtils                    RaiseLastOSError
006ef0c5 +65 PdfEditor.exe Vcl.Styles.Utils.Graphics 2764 +42 TAwesomeFont.LoadFontFromResource
006ef00d +29 PdfEditor.exe Vcl.Styles.Utils.Graphics 2696  +4 TAwesomeFont.Create
014eef3c +10 PdfEditor.exe Vcl.Styles.Utils.Graphics 2880  +1 initialization
0040a2f6 +42 PdfEditor.exe System                     202  +0 InitUnits
0040a35f +3f PdfEditor.exe System                     202  +0 @StartExe
0040f73e +42 PdfEditor.exe SysInit                            @InitExe
74ca3742 +22 KERNEL32.DLL                                     BaseThreadInitThunk

Any idea what went wrong?
Anywhere this should not raise an exception in constructor. Application cannot be started.
Best regards
Dirk

**Comment by RRUZ** [comment]
The issue is related to the [AddFontMemResourceEx](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183325(v=vs.85).aspx) function. I'm not able to reproduce the exception (maybe is related to the W10 build version). Anyway I removed  the code which raise the exception when the *AddFontMemResourceEx*  fails. So now the application will start normally. 

So try the new version and let me know the results.

**Comment by tueddy** [comment]
Thanks, i'll try it!
