### ISSUE TITLE
ActiveX style overflows over host applications

### ISSUE THREAD

**Issue by Acteevix** [RRUZ/vcl-styles-utils#177]
Hello,

I have made an ActiveX that is styled using vcl styles utils and I would like to use it as a component inside older version of Delphi that doesn't support styles (Delphi 7) or inside Internet explorer.

When loading the activex inside Delphi 7 or inside IE the style hooks partially "overflows" over all the IDE controls (object inspector, text editor ...) at design time and over other forms and components of the application containing the ActiveX at runtime, or over the internet explorer interface when loaded inside an html page. So the result is an ugly mixed colors and styles interface.

Is there a way to keep the style hooks "sanboxed" inside the ActiveX or the form containing the ActiveX ?

Thank you for your help and for this really great project !

**Comment by RRUZ** [comment]
First sorry for the very late response, Now about this issue. Unfortunately there is not a workaround for this, because the library insert a _detour_  in some _WinApi_ functions, and these functions are shared between the libraries loaded for your ActiveX and the Host App. and there is not way to restrict the _detour_ to work only on some controls.
